---
- hosts: localhost
  tasks:
    - name: Install Cython Python package
      ansible.builtin.pip:
        name: 'cython<3'
    - name: Install Certilizer Python package
      ansible.builtin.pip:
        name: 'certilizer=={{ certilizer_version }}'
